### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by lsq2020** [rsinghlab/pyaging#3]
Hello, I used Pyaging=0.3.6, but I could not install the package. I tried three methods in the help documentation, and all errors occurred:
AttributeError: 'NoneType' object has no attribute 'split'
I guess the reason is that the dependency package pybigwig package cannot be installed. Is there any solution? I use windows system
The error is as follows:

(Pyaging) C:\Users\admin>pip install Pyaging
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting Pyaging
  Using cached https://mirrors.aliyun.com/pypi/packages/46/b3/f573c6c7ca1f349503da8e6bc31f9e9b3bc0f9cd1a926cfefff2ac38edd0/pyaging-0.1.6-py3-none-any.whl (37 kB)
Requirement already satisfied: anndata<0.11.0,>=0.10.3 in c:\users\admin\anaconda3\envs\pyaging\lib\site-packages (from Pyaging) (0.10.5.post1)
Requirement already satisfied: numpy<2.0.0,>=1.26.2 in c:\users\admin\anaconda3\envs\pyaging\lib\site-packages (from Pyaging) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=2.1.3 in c:\users\admin\anaconda3\envs\pyaging\lib\site-packages (from Pyaging) (2.2.1)
Collecting pyBigWig<0.4.0,>=0.3.22 (from Pyaging)
  Using cached https://mirrors.aliyun.com/pypi/packages/f0/57/334db9a75d6941876ef282cc7eb1885a24fe71d3c6522c19f717db4f8b73/pyBigWig-0.3.22.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\admin\anaconda3\envs\Pyaging\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\admin\anaconda3\envs\Pyaging\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\admin\anaconda3\envs\Pyaging\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g85iu5lr\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g85iu5lr\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g85iu5lr\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Thankyou！！

**Comment by lcamillo** [comment]
Hi! Thanks for bringing this up. 

Could I check which version of python you are using? Currently pyaging only works on 3.9-3.11.

**Comment by osbornzhou** [comment]
pip install pyaging in python 3.9-3.11 all have this problem, maybe something wrong in setuptool?

**Comment by lcamillo** [comment]
I would recommend installing pyaging with poetry rather than with pip. Perhaps creating a new conda environment would help -- the GitHub tests passed in Windows and Linux for python 3.9-3.11.

Could you provide more details of your OS? 

Thank you!

**Comment by osbornzhou** [comment]
> I would recommend installing pyaging with poetry rather than with pip. Perhaps creating a new conda environment would help -- the GitHub tests passed in Windows and Linux for python 3.9-3.11.
> 
> Could you provide more details of your OS?
> 
> Thank you!

i use anaconda in win11! thx

**Comment by GillianGrayson** [comment]
Any updates here?
It is impossible to install one of dependencies (pybigwig) on Windows OS.
Is pyaging supported only for Unix/Linux? Maybe it will be useful to add a disclaimer about supported OS in the package description?

**Comment by lcamillo** [comment]
Apologies for the delay! I'm planning on making the pybigwig dependency optional this weekend. It should run just fine on Unix/Linux.

**Comment by lcamillo** [comment]
Apologies again for the delay. I have now made pyBigWig optional (only needed for the histone mark clocks). Could you let me know if the issue has been fixed? Thanks!

**Comment by GillianGrayson** [comment]
Thank you so much!
Everything works perfectly now! Tested all Homo Sapiens DNAm clocks with custom dataset.
Will cite you in future papers.

**Comment by lcamillo** [comment]
Great to hear! I'll close the issue now but feel free to open another one in case something is not working! Thanks again for flagging it.
